# You're free to change the jobs and the workflow logic as needed.
# Doc: https://circleci.com/docs/2.0/getting-started/#running-your-first-circleci-build
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "webserver/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r webserver/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "webserver/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
  package-validate:
    docker:
      - image: hashicorp/packer:1.5.1
    
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: validate packer build
          command: packer validate ./packer/webserver-ami.json
  packer-build:
    docker:
     - image: hashicorp/packer:1.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build webserver ami
          command: packer build webserver-ami.json
          working_directory: ~/repo/packer
      - persist_to_workspace:
          root: .
          paths:
            - packer/manifest.json
workflows:
  version: 2
  build-and-package:
    jobs:
      - build
      - packer-validate
      - packer-build
        requires:
          - build
          - packer-validate

      
